package com.jbarseg.IoC;

public class SecretaryEmployee implements Employees {

    //We are going to use this class to explain the second method to own to do the Dependency Injection
    //We have to create the setter of the variable reportsCreator

    private ReportsCreator reportsCreator;
    private String email;
    private String businessName;

    public void setReportsCreator(ReportsCreator reportsCreator) {
        this.reportsCreator = reportsCreator;
    }

    @Override
    public String getTasks() {
        return "Manage the agenda of the bosses";
    }

    @Override
    public String getReport() {
        // TODO Auto-generated method stub
        return "Report generated by the secretary: " + reportsCreator.getReport();
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getBusinessName() {
        return businessName;
    }

    public void setBusinessName(String businessName) {
        this.businessName = businessName;
    }

}
