package com.jbarseg.IoC;

public class SecretaryEmployee implements Employees {

    //We are going to use this class to explain the second method to own to do the Dependency Injection
    //We have to create the setter of the variable reportsCreator

    private ReportsCreator reportsCreator;

    public void setReportsCreator(ReportsCreator reportsCreator) {
        this.reportsCreator = reportsCreator;
    }

    @Override
    public String getTasks() {
        return "Manage the agenda of the bosses";
    }

    @Override
    public String getReport() {
        // TODO Auto-generated method stub
        return "Report generated by the secretary" + reportsCreator.getReport();
    }

}
